include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/Pods/**
    - android/**

linter:
  rules:
    # Style rules
    always_put_control_body_on_new_line: true
    always_specify_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_interpolation_to_compose_strings: true

    # Correctness
    avoid_types_on_closure_parameters: true
    await_only_futures: true
    depend_on_referenced_packages: true
    use_build_context_synchronously: true

    # Deprecated / Removed
    # Removed deprecated lints like withOpacity (handled in code)
    
    # Optional rules
    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: false
    unnecessary_null_comparison: true
    deprecated_member_use: true
