include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/Pods/**
    - android/**

linter:
  rules:
    always_specify_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
    prefer_single_quotes: true
