name: lifemix_app
description: LifeMix - Wellness, Habits, and Tasks Tracker
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  shared_preferences: ^2.5.3
  http: ^1.5.0
  percent_indicator: ^4.2.5
  cupertino_icons: ^1.0.5
  device_info_plus: ^11.5.0
  google_mobile_ads: ^6.0.0
  huawei_ads: ^13.4.77+300
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  in_app_purchase: ^4.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

